-- ============================================
-- Script de inicialización de base de datos
-- ENCOMIEXPRESS
-- Convención: snake_case en tablas y columnas
-- ============================================

-- Crear base de datos (ejecutar primero en psql)
-- CREATE DATABASE encomiexpress;

-- ============================================
-- TABLAS
-- ============================================

CREATE TABLE rol (
  id_rol      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      VARCHAR(50)  NOT NULL,
  descripcion VARCHAR(200),
  habilitado  BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE permiso (
  id_permiso  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      VARCHAR(50)  NOT NULL,
  descripcion VARCHAR(200),
  habilitado  BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE rol_permiso (
  id_rol     INTEGER NOT NULL,
  id_permiso INTEGER NOT NULL,
  PRIMARY KEY (id_rol, id_permiso)
);

CREATE TABLE usuario (
  id_usuario            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_rol                INTEGER NOT NULL,
  tipo_identificacion   VARCHAR(20)  NOT NULL,
  numero_identificacion VARCHAR(20)  UNIQUE NOT NULL,
  nombre                VARCHAR(100) NOT NULL,
  apellido              VARCHAR(100) NOT NULL,
  telefono              VARCHAR(20),
  email                 VARCHAR(150) UNIQUE NOT NULL,
  password              VARCHAR(255) NOT NULL,
  habilitado            BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE conductor (
  id_conductor         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario           INTEGER UNIQUE NOT NULL,
  categorias_licencia  JSONB NOT NULL DEFAULT '[]',
  numero_licencia      VARCHAR(20) UNIQUE,
  estado               VARCHAR(30) NOT NULL DEFAULT 'Disponible',
  habilitado           BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE cliente (
  id_cliente            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_identificacion   VARCHAR(20)  NOT NULL,
  numero_identificacion VARCHAR(20)  UNIQUE NOT NULL,
  nombre                VARCHAR(100) NOT NULL,
  apellido              VARCHAR(100) NOT NULL,
  telefono              VARCHAR(20),
  email                 VARCHAR(150),
  direccion             VARCHAR(255),
  -- Municipio del remitente — para saber a dónde devolver un paquete si el
  -- destinatario nunca lo recoge (ver LOGICA.md).
  id_destino            INTEGER,
  habilitado            BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE propietario_vehiculo (
  id_propietario        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_identificacion   VARCHAR(20)  NOT NULL,
  numero_identificacion VARCHAR(20)  UNIQUE NOT NULL,
  nombre                VARCHAR(100) NOT NULL,
  apellido              VARCHAR(100) NOT NULL,
  telefono              VARCHAR(20),
  email                 VARCHAR(150),
  tipo_flota            VARCHAR(50),
  habilitado            BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE vehiculo (
  id_vehiculo                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_propietario               INTEGER NOT NULL,
  placa                        VARCHAR(10) UNIQUE NOT NULL,
  tarjeta_propiedad            VARCHAR(50),
  marca                        VARCHAR(50),
  modelo                       VARCHAR(50),
  color                        VARCHAR(30),
  tipo                         VARCHAR(50),
  origen                       VARCHAR(20) NOT NULL DEFAULT 'Propio',
  capacidad                    DECIMAL(10,2) NOT NULL,
  estado                       VARCHAR(30) NOT NULL DEFAULT 'Disponible',
  habilitado                   BOOLEAN NOT NULL DEFAULT true,
  fecha_registro               DATE,
  vencimiento_soat             DATE NOT NULL,
  vencimiento_revision_tecnica DATE NOT NULL,
  vencimiento_seguro_terceros  DATE NOT NULL
);

CREATE TABLE destino (
  id_destino   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  departamento VARCHAR(60)   NOT NULL,
  ciudad       VARCHAR(60)   NOT NULL,
  direccion    VARCHAR(200),
  tarifa_base  DECIMAL(12,2) NOT NULL DEFAULT 0,
  habilitado   BOOLEAN NOT NULL DEFAULT true
);

-- Fila única (id siempre 1) de valores de negocio globales editables desde el
-- panel, sin necesidad de redesplegar el backend. Las tres tarifas se editan
-- desde Ventas — mismo patrón de control (candado para desbloquear edición)
-- replicado para cada una.
CREATE TABLE configuracion (
  id                    INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  tarifa_por_kg_hierro  DECIMAL(10,2) NOT NULL DEFAULT 450,
  tarifa_por_kg_normal  DECIMAL(10,2) NOT NULL DEFAULT 650,
  tarifa_por_paquete    DECIMAL(10,2) NOT NULL DEFAULT 10000
);

CREATE TABLE ruta (
  id_ruta               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_destino            INTEGER NOT NULL,
  -- Si está lleno, esta fila es el viaje de regreso de esa otra ruta (mismo
  -- convoy, corredor invertido) — ver "Viaje de regreso vinculado" en LOGICA.md.
  id_ruta_ida           INTEGER,
  origen                VARCHAR(150) DEFAULT 'Medellín',
  hora_salida           TIME,
  hora_llegada_estimada TIME,
  fecha_salida          DATE,
  fecha_llegada_estimada DATE,
  estado                VARCHAR(30) NOT NULL DEFAULT 'Programada',
  observaciones         TEXT,
  habilitado            BOOLEAN NOT NULL DEFAULT true,
  fecha_creacion        DATE NOT NULL DEFAULT CURRENT_DATE
);

-- Una ruta puede repartirse entre varios vehículos (cada uno con su conductor),
-- ej. cuando la carga total no cabe en un solo camión — todos salen juntos, misma
-- ruta/fecha/hora. Antes id_vehiculo/id_conductor vivían directo en "ruta" (1 solo
-- par); se movieron aquí para permitir N pares por ruta. "habilitado" es soft-delete:
-- si se quita un vehículo de una ruta que ya tiene paquetes asignados, se inhabilita
-- en vez de borrarse, para no perder la trazabilidad de esos paquetes.
CREATE TABLE ruta_vehiculo_conductor (
  id_ruta_vehiculo_conductor INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_ruta       INTEGER NOT NULL,
  id_vehiculo   INTEGER NOT NULL,
  id_conductor  INTEGER NOT NULL,
  habilitado    BOOLEAN NOT NULL DEFAULT true
);

-- Paradas intermedias del corredor de una ruta (municipios donde el convoy deja
-- paquetes en el camino, ej. Medellín → Yarumal → Valdivia → Tarazá → Caucasia) —
-- información aditiva, no reemplaza a ruta.id_destino (que sigue siendo el destino
-- final del tramo troncal). fecha/hora_llegada_estimada son opcionales, reservadas
-- para cuando Ventas recalcule la fecha estimada de entrega por parada.
CREATE TABLE ruta_parada (
  id_ruta_parada          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_ruta                 INTEGER NOT NULL,
  id_destino              INTEGER NOT NULL,
  orden                   INTEGER NOT NULL,
  fecha_llegada_estimada  DATE,
  hora_llegada_estimada   TIME
);

CREATE TABLE anticipo_excedente (
  id_anticipo_excedente   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_conductor            INTEGER NOT NULL,
  id_ruta                 INTEGER NOT NULL,
  valor_anticipo          DECIMAL(12,2) NOT NULL DEFAULT 0,
  valor_gastado           DECIMAL(12,2) DEFAULT 0,
  excedente               DECIMAL(12,2) DEFAULT 0,
  estado                  VARCHAR(30) NOT NULL DEFAULT 'Entregado',
  soporte                 JSONB NOT NULL DEFAULT '[]',
  fecha_entrega           DATE,
  fecha_legalizacion      DATE,
  fecha_entrega_excedente DATE,
  habilitado              BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE encomienda_venta (
  id_encomienda_venta    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_cliente             INTEGER NOT NULL,
  id_ruta                INTEGER NOT NULL,
  fecha_registro         DATE NOT NULL DEFAULT CURRENT_DATE,
  fecha_hora_emision     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_estimada_entrega DATE,
  estado                 VARCHAR(30) NOT NULL DEFAULT 'pendiente de recogida',
  observaciones          TEXT,
  valor_servicio         DECIMAL(12,2) NOT NULL DEFAULT 0,
  total                  DECIMAL(12,2) NOT NULL DEFAULT 0,
  metodo_pago            VARCHAR(30),
  estado_pago            VARCHAR(20) NOT NULL DEFAULT 'pendiente',
  habilitado             BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE destinatario (
  id_destinatario        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_encomienda_venta    INTEGER NOT NULL UNIQUE,
  id_destino             INTEGER,
  nombre_destinatario    VARCHAR(150) NOT NULL,
  -- Documento del destinatario, mismos tipos que cliente (CC/NIT/TI/CE/PAS/RC).
  tipo_identificacion_destinatario   VARCHAR(20),
  numero_identificacion_destinatario VARCHAR(20),
  telefono_destinatario  VARCHAR(20),
  correo_destinatario    VARCHAR(150),
  direccion_destinatario VARCHAR(255)
);

CREATE TABLE paquete (
  id_paquete                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_encomienda_venta         INTEGER NOT NULL,
  id_ruta_vehiculo_conductor  INTEGER NOT NULL,
  numero_guia                 VARCHAR(50) UNIQUE NOT NULL,
  descripcion_contenido       TEXT,
  peso                        DECIMAL(8,2) NOT NULL,
  alto                        DECIMAL(8,2),
  ancho                       DECIMAL(8,2),
  profundidad                 DECIMAL(8,2)
  ,tipo_carga                  VARCHAR(20) NOT NULL DEFAULT 'normal' CHECK (tipo_carga IN ('hierro','normal'))
  ,estado                      VARCHAR(30) NOT NULL DEFAULT 'Por entregar'
  ,observacion_estado         TEXT
  ,fecha_ultimo_estado        TIMESTAMPTZ
  ,foto_entrega               TEXT
  ,id_conductor_entrega       INTEGER
);

-- Municipios donde un conductor ha hecho de repartidor local (entrega puerta a
-- puerta), distinto del tramo troncal entre ciudades (ruta_vehiculo_conductor).
-- Se puebla solo desde encomiendaService.asignarRepartidorLocal, no hace falta
-- una pantalla aparte para registrar coberturas de antemano.
CREATE TABLE conductor_sede (
  id_conductor_sede  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_conductor       INTEGER NOT NULL,
  id_destino         INTEGER NOT NULL,
  habilitado         BOOLEAN NOT NULL DEFAULT true
);

-- ============================================
-- COMENTARIOS
-- ============================================

COMMENT ON COLUMN permiso.nombre IS 'ej: listar_usuario, registrar_cliente, actualizar_encomienda';
COMMENT ON COLUMN usuario.password IS 'hash bcrypt';
COMMENT ON COLUMN vehiculo.placa IS 'Colombia: 6 chars';
COMMENT ON COLUMN anticipo_excedente.soporte IS 'Array JSONB de URLs de Cloudinary — uno o varios comprobantes';
COMMENT ON COLUMN ruta.estado IS 'Programada | En Ruta | Completada | Cancelada';
COMMENT ON COLUMN ruta.origen IS 'Ciudad de origen de la ruta (texto libre, dato base: Medellín)';
COMMENT ON COLUMN encomienda_venta.estado IS 'Programada | En Ruta | Entregada | Completada con novedades | Cancelada';
COMMENT ON COLUMN paquete.estado IS 'Por entregar | En sede de destino | Entregado | Devuelto';
COMMENT ON COLUMN destinatario.id_destino IS 'Municipio al que se envía el paquete (mismo catálogo que ruta.id_destino) — decisión comercial capturada al vender, distinta de qué Ruta administrativa termine asignándose. Nullable a nivel de columna por flexibilidad (igual que ruta.fecha_llegada_estimada); obligatorio en el flujo real vía encomiendasValidator.';
COMMENT ON COLUMN paquete.tipo_carga IS 'hierro | normal — determina qué tarifa por kg (tarifa_por_kg_hierro / tarifa_por_kg_normal) aplica en el cálculo de valorServicio';

-- ============================================
-- LLAVES FORÁNEAS
-- ============================================

ALTER TABLE rol_permiso ADD FOREIGN KEY (id_rol) REFERENCES rol (id_rol);
ALTER TABLE rol_permiso ADD FOREIGN KEY (id_permiso) REFERENCES permiso (id_permiso);
ALTER TABLE usuario ADD FOREIGN KEY (id_rol) REFERENCES rol (id_rol);
ALTER TABLE conductor ADD FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario);
ALTER TABLE vehiculo ADD FOREIGN KEY (id_propietario) REFERENCES propietario_vehiculo (id_propietario);
ALTER TABLE ruta ADD FOREIGN KEY (id_destino) REFERENCES destino (id_destino);
ALTER TABLE ruta_vehiculo_conductor ADD FOREIGN KEY (id_ruta) REFERENCES ruta (id_ruta);
ALTER TABLE ruta_vehiculo_conductor ADD FOREIGN KEY (id_vehiculo) REFERENCES vehiculo (id_vehiculo);
ALTER TABLE ruta_vehiculo_conductor ADD FOREIGN KEY (id_conductor) REFERENCES conductor (id_conductor);
-- Un mismo vehículo/conductor no puede repetirse dos veces (entre pares habilitados)
-- dentro de la misma ruta — parcial en habilitado=true para poder reusar el par
-- después de quitarlo (inhabilitado) y volver a agregarlo.
CREATE UNIQUE INDEX uq_rvc_ruta_vehiculo_activo ON ruta_vehiculo_conductor (id_ruta, id_vehiculo) WHERE habilitado = true;
CREATE UNIQUE INDEX uq_rvc_ruta_conductor_activo ON ruta_vehiculo_conductor (id_ruta, id_conductor) WHERE habilitado = true;
ALTER TABLE ruta ADD FOREIGN KEY (id_ruta_ida) REFERENCES ruta (id_ruta);
-- Una ida solo puede tener UN regreso enlazado.
CREATE UNIQUE INDEX uq_ruta_ida ON ruta (id_ruta_ida) WHERE id_ruta_ida IS NOT NULL;
ALTER TABLE ruta_parada ADD FOREIGN KEY (id_ruta) REFERENCES ruta (id_ruta);
ALTER TABLE ruta_parada ADD FOREIGN KEY (id_destino) REFERENCES destino (id_destino);
-- Un mismo municipio no puede repetirse dos veces como parada de la misma ruta, ni
-- dos paradas de la misma ruta pueden compartir la misma posición en el corredor.
CREATE UNIQUE INDEX uq_parada_ruta_destino ON ruta_parada (id_ruta, id_destino);
CREATE UNIQUE INDEX uq_parada_ruta_orden ON ruta_parada (id_ruta, orden);
ALTER TABLE anticipo_excedente ADD FOREIGN KEY (id_conductor) REFERENCES conductor (id_conductor);
ALTER TABLE anticipo_excedente ADD FOREIGN KEY (id_ruta) REFERENCES ruta (id_ruta);
ALTER TABLE cliente ADD FOREIGN KEY (id_destino) REFERENCES destino (id_destino);
ALTER TABLE encomienda_venta ADD FOREIGN KEY (id_cliente) REFERENCES cliente (id_cliente);
ALTER TABLE encomienda_venta ADD FOREIGN KEY (id_ruta) REFERENCES ruta (id_ruta);
ALTER TABLE destinatario ADD FOREIGN KEY (id_encomienda_venta) REFERENCES encomienda_venta (id_encomienda_venta);
ALTER TABLE destinatario ADD FOREIGN KEY (id_destino) REFERENCES destino (id_destino);
ALTER TABLE paquete ADD FOREIGN KEY (id_encomienda_venta) REFERENCES encomienda_venta (id_encomienda_venta);
ALTER TABLE paquete ADD FOREIGN KEY (id_ruta_vehiculo_conductor) REFERENCES ruta_vehiculo_conductor (id_ruta_vehiculo_conductor);
ALTER TABLE paquete ADD FOREIGN KEY (id_conductor_entrega) REFERENCES conductor (id_conductor);
ALTER TABLE conductor_sede ADD FOREIGN KEY (id_conductor) REFERENCES conductor (id_conductor);
ALTER TABLE conductor_sede ADD FOREIGN KEY (id_destino) REFERENCES destino (id_destino);
-- Un mismo conductor no queda dos veces como repartidor activo del mismo
-- municipio — igual que uq_rvc_ruta_vehiculo_activo, parcial en habilitado=true.
CREATE UNIQUE INDEX uq_conductor_sede_activo ON conductor_sede (id_conductor, id_destino) WHERE habilitado = true;

-- ============================================
-- DATOS INICIALES
-- ============================================

-- Roles
INSERT INTO rol (nombre, descripcion) VALUES
('admin',    'Administrador del sistema con acceso total'),
('conductor','Conductor de vehículo');

-- Permisos granulares
INSERT INTO permiso (nombre, descripcion, habilitado) VALUES
('listar_usuario',      'Listar usuarios',           true),
('registrar_usuario',   'Registrar usuarios',         true),
('consultar_usuario',   'Consultar usuarios',         true),
('actualizar_usuario',  'Actualizar usuarios',        true),
('inhabilitar_usuario', 'Inhabilitar usuarios',       true),
('listar_rol',          'Listar roles',               true),
('registrar_rol',       'Registrar roles',            true),
('consultar_rol',       'Consultar roles',            true),
('actualizar_rol',      'Actualizar roles',           true),
('inhabilitar_rol',     'Inhabilitar roles',          true),
('listar_cliente',      'Listar clientes',            true),
('registrar_cliente',   'Registrar clientes',         true),
('consultar_cliente',   'Consultar clientes',         true),
('actualizar_cliente',  'Actualizar clientes',        true),
('inhabilitar_cliente', 'Inhabilitar clientes',       true),
('listar_vehiculo',     'Listar vehículos',           true),
('registrar_vehiculo',  'Registrar vehículos',        true),
('consultar_vehiculo',  'Consultar vehículos',        true),
('actualizar_vehiculo', 'Actualizar vehículos',       true),
('inhabilitar_vehiculo','Inhabilitar vehículos',      true),
('listar_conductor',    'Listar conductores',         true),
('registrar_conductor', 'Registrar conductores',      true),
('consultar_conductor', 'Consultar conductores',      true),
('actualizar_conductor','Actualizar conductores',     true),
('inhabilitar_conductor','Inhabilitar conductores',   true),
('listar_destino',      'Listar destinos',            true),
('registrar_destino',   'Registrar destinos',         true),
('consultar_destino',   'Consultar destinos',         true),
('actualizar_destino',  'Actualizar destinos',        true),
('inhabilitar_destino', 'Inhabilitar destinos',       true),
('listar_ruta',         'Listar rutas',               true),
('registrar_ruta',      'Registrar rutas',            true),
('consultar_ruta',      'Consultar rutas',            true),
('actualizar_ruta',     'Actualizar rutas',           true),
('inhabilitar_ruta',    'Inhabilitar rutas',          true),
('listar_anticipo',     'Listar anticipos',           true),
('registrar_anticipo',  'Registrar anticipos',        true),
('consultar_anticipo',  'Consultar anticipos',        true),
('actualizar_anticipo', 'Actualizar anticipos',       true),
('inhabilitar_anticipo','Inhabilitar anticipos',      true),
('listar_venta',      'Listar ventas',           true),
('registrar_venta',   'Registrar ventas',        true),
('consultar_venta',   'Consultar ventas',        true),
('actualizar_venta',  'Actualizar ventas',       true),
('inhabilitar_venta', 'Inhabilitar ventas',      true),
('listar_propietario',     'Listar propietarios',          true),
('registrar_propietario',  'Registrar propietarios',       true),
('consultar_propietario',  'Consultar propietarios',       true),
('actualizar_propietario', 'Actualizar propietarios',      true),
('inhabilitar_propietario','Inhabilitar propietarios',     true),
('ver_dashboard',          'Ver dashboard',                true);

-- Asignar todos los permisos al admin
INSERT INTO rol_permiso (id_rol, id_permiso)
SELECT 1, id_permiso FROM permiso WHERE habilitado = true;

-- El usuario admin NO se crea aquí a propósito: correr `npm run db:seed`
-- (src/config/seed.js) después de este script — toma la contraseña de la
-- variable de entorno ADMIN_INITIAL_PASSWORD en vez de dejarla escrita en
-- este archivo (que vive en git).

-- Destinos del Bajo Cauca Antioqueño y conexiones
INSERT INTO destino (departamento, ciudad, tarifa_base) VALUES
('Antioquia', 'Puerto Valdivia',   0),
('Antioquia', 'Tarazá',            0),
('Antioquia', 'Cáceres',           0),
('Antioquia', 'Caucasia',          0),
('Antioquia', 'Nechí',             0),
('Antioquia', 'El Bagre',          0),
('Antioquia', 'Zaragoza',          0),
('Córdoba',   'Montelíbano',       0),
('Córdoba',   'Puerto Libertador', 0),
('Córdoba',   'Montería',          0),
('Córdoba',   'Ayapel',            0);

-- Configuración global — las tres tarifas nacen con los valores reales que dio
-- el cliente: $450/kg para carga "hierro", $650/kg para carga "normal", y
-- $10.000 por paquete, editables las tres desde el panel (módulo Ventas).
INSERT INTO configuracion (id, tarifa_por_kg_hierro, tarifa_por_kg_normal, tarifa_por_paquete) VALUES (1, 450, 650, 10000);