-- ============================================
-- Script de inicialización de base de datos
-- ENCOMIEXPRESS
-- Convención: snake_case en tablas y columnas
-- ============================================

-- Crear base de datos (ejecutar primero en psql)
-- CREATE DATABASE encomiexpress;

-- ============================================
-- TABLAS
-- ============================================

CREATE TABLE rol (
  id_rol      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      VARCHAR(50)  NOT NULL,
  descripcion VARCHAR(200),
  habilitado  BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE permiso (
  id_permiso  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      VARCHAR(50)  NOT NULL,
  descripcion VARCHAR(200),
  habilitado  BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE rol_permiso (
  id_rol     INTEGER NOT NULL,
  id_permiso INTEGER NOT NULL,
  PRIMARY KEY (id_rol, id_permiso)
);

CREATE TABLE usuario (
  id_usuario            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_rol                INTEGER NOT NULL,
  tipo_identificacion   VARCHAR(20)  NOT NULL,
  numero_identificacion VARCHAR(20)  UNIQUE NOT NULL,
  nombre                VARCHAR(100) NOT NULL,
  apellido              VARCHAR(100) NOT NULL,
  telefono              VARCHAR(20),
  email                 VARCHAR(150) UNIQUE NOT NULL,
  password              VARCHAR(255) NOT NULL,
  habilitado            BOOLEAN NOT NULL DEFAULT true,
  registro_pendiente    BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE conductor (
  id_conductor         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario           INTEGER UNIQUE NOT NULL,
  categorias_licencia  JSONB NOT NULL DEFAULT '[]',
  numero_licencia      VARCHAR(20) UNIQUE,
  estado               VARCHAR(30) NOT NULL DEFAULT 'activo',
  habilitado           BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE cliente (
  id_cliente            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_identificacion   VARCHAR(20)  NOT NULL,
  numero_identificacion VARCHAR(20)  UNIQUE NOT NULL,
  nombre                VARCHAR(100) NOT NULL,
  apellido              VARCHAR(100) NOT NULL,
  telefono              VARCHAR(20),
  email                 VARCHAR(150),
  direccion             VARCHAR(255),
  habilitado            BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE propietario_vehiculo (
  id_propietario        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_identificacion   VARCHAR(20)  NOT NULL,
  numero_identificacion VARCHAR(20)  UNIQUE NOT NULL,
  nombre                VARCHAR(100) NOT NULL,
  apellido              VARCHAR(100) NOT NULL,
  telefono              VARCHAR(20),
  email                 VARCHAR(150),
  tipo_flota            VARCHAR(50),
  habilitado            BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE vehiculo (
  id_vehiculo                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_propietario               INTEGER NOT NULL,
  placa                        VARCHAR(10) UNIQUE NOT NULL,
  tarjeta_propiedad            VARCHAR(50),
  marca                        VARCHAR(50),
  modelo                       VARCHAR(50),
  color                        VARCHAR(30),
  tipo                         VARCHAR(50),
  origen                       VARCHAR(20) NOT NULL DEFAULT 'Propio',
  capacidad                    DECIMAL(10,2) NOT NULL,
  estado                       VARCHAR(30) NOT NULL DEFAULT 'disponible',
  habilitado                   BOOLEAN NOT NULL DEFAULT true,
  fecha_registro               DATE,
  vencimiento_soat             DATE NOT NULL,
  vencimiento_revision_tecnica DATE NOT NULL,
  vencimiento_seguro_terceros  DATE NOT NULL
);

CREATE TABLE destino (
  id_destino   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  departamento VARCHAR(60)   NOT NULL,
  ciudad       VARCHAR(60)   NOT NULL,
  tarifa_base  DECIMAL(12,2) NOT NULL DEFAULT 0,
  habilitado   BOOLEAN NOT NULL DEFAULT true
);

-- Fila única (id siempre 1) de valores de negocio globales editables desde el
-- panel, sin necesidad de redesplegar el backend. Hoy solo tarifa_por_kg.
CREATE TABLE configuracion (
  id             INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  tarifa_por_kg  DECIMAL(10,2) NOT NULL DEFAULT 0
);

CREATE TABLE ruta (
  id_ruta               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_vehiculo           INTEGER NOT NULL,
  id_conductor          INTEGER NOT NULL,
  id_destino            INTEGER NOT NULL,
  nombre_ruta           VARCHAR(150),
  hora_salida           TIME,
  hora_llegada_estimada TIME,
  fecha_salida          DATE,
  estado                VARCHAR(30) NOT NULL DEFAULT 'Programada',
  observaciones         TEXT,
  habilitado            BOOLEAN NOT NULL DEFAULT true,
  fecha_creacion        DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE anticipo_excedente (
  id_anticipo_excedente   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_conductor            INTEGER NOT NULL,
  id_ruta                 INTEGER NOT NULL,
  valor_anticipo          DECIMAL(12,2) NOT NULL DEFAULT 0,
  valor_gastado           DECIMAL(12,2) DEFAULT 0,
  excedente               DECIMAL(12,2) DEFAULT 0,
  estado                  VARCHAR(30) NOT NULL DEFAULT 'pendiente',
  soporte                 JSONB NOT NULL DEFAULT '[]',
  fecha_entrega           DATE,
  fecha_legalizacion      DATE,
  fecha_entrega_excedente DATE,
  habilitado              BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE encomienda_venta (
  id_encomienda_venta    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_cliente             INTEGER NOT NULL,
  id_ruta                INTEGER NOT NULL,
  fecha_registro         DATE NOT NULL DEFAULT CURRENT_DATE,
  fecha_hora_emision     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_estimada_entrega DATE,
  estado                 VARCHAR(30) NOT NULL DEFAULT 'pendiente de recogida',
  observaciones          TEXT,
  valor_servicio         DECIMAL(12,2) NOT NULL DEFAULT 0,
  impuestos              DECIMAL(12,2) DEFAULT 0,
  total                  DECIMAL(12,2) NOT NULL DEFAULT 0,
  metodo_pago            VARCHAR(30),
  estado_pago            VARCHAR(20) NOT NULL DEFAULT 'pendiente',
  habilitado             BOOLEAN NOT NULL DEFAULT true,
  token_seguimiento      VARCHAR(64) UNIQUE
);

CREATE TABLE destinatario (
  id_destinatario        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_encomienda_venta    INTEGER NOT NULL UNIQUE,
  nombre_destinatario    VARCHAR(150) NOT NULL,
  telefono_destinatario  VARCHAR(20),
  direccion_destinatario VARCHAR(255)
);

CREATE TABLE paquete (
  id_paquete            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_encomienda_venta   INTEGER NOT NULL,
  numero_guia           VARCHAR(50) UNIQUE NOT NULL,
  descripcion_contenido TEXT,
  peso                  DECIMAL(8,2) NOT NULL,
  alto                  DECIMAL(8,2),
  ancho                 DECIMAL(8,2),
  profundidad           DECIMAL(8,2),
  valor_declarado       DECIMAL(12,2)
);

-- ============================================
-- COMENTARIOS
-- ============================================

COMMENT ON COLUMN permiso.nombre IS 'ej: listar_usuario, registrar_cliente, actualizar_encomienda';
COMMENT ON COLUMN usuario.password IS 'hash bcrypt';
COMMENT ON COLUMN vehiculo.placa IS 'Colombia: 6 chars';
COMMENT ON COLUMN anticipo_excedente.soporte IS 'Array JSONB de URLs de Cloudinary — uno o varios comprobantes';
COMMENT ON COLUMN ruta.estado IS 'Programada | En Curso | Completada | Cancelada';
COMMENT ON COLUMN encomienda_venta.estado IS 'pendiente de recogida | en recogida | programada | en tránsito | entregado | devuelto';
COMMENT ON COLUMN encomienda_venta.token_seguimiento IS 'Token único para seguimiento público vía enlace';

-- ============================================
-- LLAVES FORÁNEAS
-- ============================================

ALTER TABLE rol_permiso ADD FOREIGN KEY (id_rol) REFERENCES rol (id_rol);
ALTER TABLE rol_permiso ADD FOREIGN KEY (id_permiso) REFERENCES permiso (id_permiso);
ALTER TABLE usuario ADD FOREIGN KEY (id_rol) REFERENCES rol (id_rol);
ALTER TABLE conductor ADD FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario);
ALTER TABLE vehiculo ADD FOREIGN KEY (id_propietario) REFERENCES propietario_vehiculo (id_propietario);
ALTER TABLE ruta ADD FOREIGN KEY (id_vehiculo) REFERENCES vehiculo (id_vehiculo);
ALTER TABLE ruta ADD FOREIGN KEY (id_conductor) REFERENCES conductor (id_conductor);
ALTER TABLE ruta ADD FOREIGN KEY (id_destino) REFERENCES destino (id_destino);
ALTER TABLE anticipo_excedente ADD FOREIGN KEY (id_conductor) REFERENCES conductor (id_conductor);
ALTER TABLE anticipo_excedente ADD FOREIGN KEY (id_ruta) REFERENCES ruta (id_ruta);
ALTER TABLE encomienda_venta ADD FOREIGN KEY (id_cliente) REFERENCES cliente (id_cliente);
ALTER TABLE encomienda_venta ADD FOREIGN KEY (id_ruta) REFERENCES ruta (id_ruta);
ALTER TABLE destinatario ADD FOREIGN KEY (id_encomienda_venta) REFERENCES encomienda_venta (id_encomienda_venta);
ALTER TABLE paquete ADD FOREIGN KEY (id_encomienda_venta) REFERENCES encomienda_venta (id_encomienda_venta);

-- ============================================
-- DATOS INICIALES
-- ============================================

-- Roles
INSERT INTO rol (nombre, descripcion) VALUES
('admin',    'Administrador del sistema con acceso total'),
('conductor','Conductor de vehículo');

-- Permisos granulares
INSERT INTO permiso (nombre, descripcion, habilitado) VALUES
('listar_usuario',      'Listar usuarios',           true),
('registrar_usuario',   'Registrar usuarios',         true),
('consultar_usuario',   'Consultar usuarios',         true),
('actualizar_usuario',  'Actualizar usuarios',        true),
('inhabilitar_usuario', 'Inhabilitar usuarios',       true),
('listar_rol',          'Listar roles',               true),
('registrar_rol',       'Registrar roles',            true),
('consultar_rol',       'Consultar roles',            true),
('actualizar_rol',      'Actualizar roles',           true),
('inhabilitar_rol',     'Inhabilitar roles',          true),
('listar_cliente',      'Listar clientes',            true),
('registrar_cliente',   'Registrar clientes',         true),
('consultar_cliente',   'Consultar clientes',         true),
('actualizar_cliente',  'Actualizar clientes',        true),
('inhabilitar_cliente', 'Inhabilitar clientes',       true),
('listar_vehiculo',     'Listar vehículos',           true),
('registrar_vehiculo',  'Registrar vehículos',        true),
('consultar_vehiculo',  'Consultar vehículos',        true),
('actualizar_vehiculo', 'Actualizar vehículos',       true),
('inhabilitar_vehiculo','Inhabilitar vehículos',      true),
('listar_conductor',    'Listar conductores',         true),
('registrar_conductor', 'Registrar conductores',      true),
('consultar_conductor', 'Consultar conductores',      true),
('actualizar_conductor','Actualizar conductores',     true),
('inhabilitar_conductor','Inhabilitar conductores',   true),
('listar_destino',      'Listar destinos',            true),
('registrar_destino',   'Registrar destinos',         true),
('consultar_destino',   'Consultar destinos',         true),
('actualizar_destino',  'Actualizar destinos',        true),
('inhabilitar_destino', 'Inhabilitar destinos',       true),
('listar_ruta',         'Listar rutas',               true),
('registrar_ruta',      'Registrar rutas',            true),
('consultar_ruta',      'Consultar rutas',            true),
('actualizar_ruta',     'Actualizar rutas',           true),
('inhabilitar_ruta',    'Inhabilitar rutas',          true),
('listar_anticipo',     'Listar anticipos',           true),
('registrar_anticipo',  'Registrar anticipos',        true),
('consultar_anticipo',  'Consultar anticipos',        true),
('actualizar_anticipo', 'Actualizar anticipos',       true),
('inhabilitar_anticipo','Inhabilitar anticipos',      true),
('listar_venta',      'Listar ventas',           true),
('registrar_venta',   'Registrar ventas',        true),
('consultar_venta',   'Consultar ventas',        true),
('actualizar_venta',  'Actualizar ventas',       true),
('inhabilitar_venta', 'Inhabilitar ventas',      true),
('listar_propietario',     'Listar propietarios',          true),
('registrar_propietario',  'Registrar propietarios',       true),
('consultar_propietario',  'Consultar propietarios',       true),
('actualizar_propietario', 'Actualizar propietarios',      true),
('inhabilitar_propietario','Inhabilitar propietarios',     true),
('ver_dashboard',          'Ver dashboard',                true);

-- Asignar todos los permisos al admin
INSERT INTO rol_permiso (id_rol, id_permiso)
SELECT 1, id_permiso FROM permiso WHERE habilitado = true;

-- El usuario admin NO se crea aquí a propósito: correr `npm run db:seed`
-- (src/config/seed.js) después de este script — toma la contraseña de la
-- variable de entorno ADMIN_INITIAL_PASSWORD en vez de dejarla escrita en
-- este archivo (que vive en git).

-- Destinos del Bajo Cauca Antioqueño y conexiones
INSERT INTO destino (departamento, ciudad, tarifa_base) VALUES
('Antioquia', 'Puerto Valdivia',   0),
('Antioquia', 'Tarazá',            0),
('Antioquia', 'Cáceres',           0),
('Antioquia', 'Caucasia',          0),
('Antioquia', 'Nechí',             0),
('Antioquia', 'El Bagre',          0),
('Antioquia', 'Zaragoza',          0),
('Córdoba',   'Montelíbano',       0),
('Córdoba',   'Puerto Libertador', 0),
('Córdoba',   'Montería',          0),
('Córdoba',   'Ayapel',            0);

-- Configuración global — tarifa_por_kg queda en 0 a propósito: hay que
-- definirla desde el panel (Destinos → Tarifa por kg) antes de que la
-- fórmula de precio por peso en Ventas sume algo.
INSERT INTO configuracion (id, tarifa_por_kg) VALUES (1, 0);